"""Create IK Rigs + IK Retargeters PROGRAMMATICALLY (UE 5.8) -- the automation
unlock: after this script, batch retargeting needs zero editor clicks.

Run HEADLESSLY (preferred on this machine -- in-editor python has crashed it;
headless completes all work + saves, only the shutdown may crash cosmetically):

  "C:\\Program Files\\Epic Games\\UE_5.8\\Engine\\Binaries\\Win64\\UnrealEditor-Cmd.exe" ^
      "D:\\GAME_CORE 5.8\\GAME_CORE.uproject" ^
      -ExecutePythonScript="D:\\GAME_CORE 5.8\\Tools\\setup_retargeters.py" ^
      -stdout -unattended -nosplash -nosound

(or, if the editor is already open: Cmd console ->
      py "D:/GAME_CORE 5.8/Tools/setup_retargeters.py")

WHAT IT DOES (per PAIR below; every step isolated, PASS/FAIL/SKIP summary):
  1. Resolve source/target SkeletalMeshes (verifies the pack's AnimSequences
     actually use the source mesh's Skeleton; auto-rediscovers by skeleton
     match when the hardcoded path is stale).
  2. Create (or reuse) an IK Rig per mesh in /Game/Arena/Retargeters:
     auto-chains via ApplyAutoGeneratedRetargetDefinition() -- the same
     template characterizer the editor's right-click 'Retarget Animations'
     flow uses (UE4/UE5/UEFN mannequin bones all match templates). For
     unknown skeletons (Stone Golem) it degrades to a FUZZY BONE-NAME MAPPER:
     bones are read from the mesh at runtime, mapped by name+topology into
     the characterizer's canonical chain names (Spine/Neck/Head/L-R
     Clavicle/Arm/Leg), and logged as a loud table.
  3. Create (or reuse) the IK Retargeter, wire source/target rigs, rebuild
     the 5.8 default op stack, AutoMapChains (Exact for template rigs, Fuzzy
     otherwise), regenerate + auto-align the target retarget pose, and
     disable the Run-IK op (editor auto-flow parity: auto-IK isn't robust).
     Chain mapping is verified by read-back and logged as a table.
  4. Force-save everything (mark dirty + save only_if_is_dirty=False +
     on-disk mtime verify).
  5. DO_BATCH: invoke IKRetargetBatchOperation.duplicate_and_retarget per
     pair's anim batch (reimplemented locally from the proven
     Tools/batch_retarget_anims.py call handling -- that file is NOT edited).

DEGRADATION: every missing API prints the exact per-pair MANUAL recipe (the
integrate_golem_minion.py MANUAL block) instead of half-working. Nothing here
pops dialogs; everything is unattended-safe.

API SURFACE (verified against the 5.8 engine sources on this machine,
C:\\Program Files\\Epic Games\\UE_5.8\\Engine\\Plugins\\Animation\\IKRig\\Source):
  - IKRigDefinitionFactory.CreateNewIKRigAsset(path, name)   [BlueprintCallable]
  - IKRigController: GetController / SetSkeletalMesh /
    ApplyAutoGeneratedRetargetDefinition / ApplyAutoFBIK / AddRetargetChain /
    SetRetargetRoot (DisplayName SetPelvisBone) / GetRetargetChains
  - IKRetargetFactory: trivial NewObject factory, NO ConfigureProperties
    dialog -> safe with AssetTools.create_asset headless
  - IKRetargeterController: GetController / SetIKRig / RemoveAllOps /
    AddDefaultOps (5.8 op stack: PelvisMotion, FKChains, RunIKRig,
    RootMotion, CurveRemap) / AutoMapChains(EAutoMapChainType, bForce
    [, OpName=None -> ALL ops]) / GetSourceChain / ResetRetargetPose /
    AutoAlignAllBones / GetNumRetargetOps / GetOpController /
    SetRetargetOpEnabled / SetPreviewMesh
  - IKRetargetBatchOperation.duplicate_and_retarget(assets, src_mesh,
    tgt_mesh, rtg, search, replace, prefix, suffix[, target_path=...]) --
    first 8 positional stable, target_path is the 5.8 destination kwarg
    (TypeError fallback: 8-arg + rename_asset move, same as the proven file)
  - Canonical chain names (FCharacterizationStandard): Spine, Neck, Head,
    LeftLeg/RightLeg, LeftClavicle/RightClavicle, LeftArm/RightArm -- the
    fuzzy mapper emits THESE so Exact/Fuzzy automap lines up.

HARD RULES honored: no struct-array element write-backs (controllers are
native calls, verified by re-read); force-save + mtime verify; GC every ~12
asset ops; no Nanite/texture work; writes ONLY inside /Game/Arena/Retargeters
and each pair's declared output folder; montage-mutation caveat respected
(batch outputs are fresh per-character copies; never share them).
"""

import os
import re
import traceback

import unreal

# ---------------------------------------------------------------------------
# Config / constants
# ---------------------------------------------------------------------------

TAG = "[SetupRTG]"

RTG_DIR = "/Game/Arena/Retargeters"      # rigs + retargeters land here
UEFN_MESH = "/Game/Characters/UEFN_Mannequin/Meshes/SKM_UEFN_Mannequin"
GOLEM_MESH = "/Game/Stone_Golem/mesh/SKM_Stone_Golem"

DO_BATCH = os.environ.get("SETUP_RTG_BATCH", "1") != "0"
                         # flag-gated (default True): run the anim batches
                         # after asset setup; set SETUP_RTG_BATCH=0 for an
                         # assets-only validation pass
ONLY_PAIRS = [p for p in os.environ.get("SETUP_RTG_PAIRS", "").split(",") if p]
                         # optional comma-separated pair-name filter, e.g.
                         # SETUP_RTG_PAIRS=Fighter to (re)run one pack alone
                         # (everything is idempotent -- already-retargeted
                         # outputs are skipped, existing rigs reused)
FORCE_RECONFIGURE = False  # True = rewire existing retargeters even if they verify
AUTO_ALIGN = True        # editor auto-flow parity: auto-align target retarget pose
GC_EVERY = 12            # collect_garbage cadence (16 GB RAM budget)

# Each PAIR: source/target skeleton paths are DOCUMENTATION (the operative
# handles are the skeletal meshes -- that is what rigs/retargeters bind);
# anim_folders/out_folder/prefix define the DO_BATCH pass.
PAIRS = [
    dict(
        name="Fighter",
        # src skeleton: /Game/Fighter_Animations/Demo/Mannequin_UE4/Character/Mesh/UE4_Mannequin_Skeleton
        # tgt skeleton: /Game/Characters/UEFN_Mannequin/Meshes/SK_UEFN_Mannequin
        source_mesh="/Game/Fighter_Animations/Demo/Mannequin_UE4/Character/Mesh/SK_Mannequin",
        target_mesh=UEFN_MESH,
        source_rig_name="IK_Fighter_UE4Manny",
        target_rig_name="IK_UEFN_Mannequin_Auto",
        retargeter=RTG_DIR + "/RTG_Fighter_to_UEFN",
        # Sequence1 ONLY: the pack ships two parallel trees (Sequence1/ and
        # Sequence2/) with 473 identical basenames -- scanning both collides
        # in the flat out_folder and trips run_batch's name guard. Sequences
        # only (wire builds its own montages), and ONLY the ~17 sequences
        # wire_new_animations.py actually consumes (16 GB budget; the whole
        # pack is 1380 assets).
        anim_folders=["/Game/Fighter_Animations/Animation/Sequence1"],
        classes=("AnimSequence",),
        include_regex=r"(?i)^(combo_05-\d.*|hit_heavy.*|parry_[lr](_seq)?"
                      r"|charge_attack.*|attack_air_to_floor_01.*"
                      r"|run_attack_01.*)(_seq)?$",
        # FOLDER CONTRACT: wire_new_animations.py step 2 scans this folder
        # (in addition to its legacy Combo_05/Hit/BOSS dirs) -- keep in sync.
        out_folder="/Game/Retargeted_Animations/Fighter",
        prefix="FTR_", search="", replace="",
    ),
    dict(
        name="RamsterZ",
        # src skeleton: /Game/RamsterZ_FreeAnims_Volume1/Demo/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton
        source_mesh="/Game/RamsterZ_FreeAnims_Volume1/Demo/Mannequin/Character/Mesh/SK_Mannequin",
        target_mesh=UEFN_MESH,
        source_rig_name="IK_RamsterZ_UE4Manny",
        target_rig_name="IK_UEFN_Mannequin_Auto",   # shared with Fighter (same mesh)
        retargeter=RTG_DIR + "/RTG_RamsterZ_to_UEFN",
        anim_folders=["/Game/RamsterZ_FreeAnims_Volume1/AnimationSequence"],
        classes=("AnimSequence", "AnimMontage"),
        include_regex="",
        out_folder="/Game/Retargeted_Animations/RamsterZ",
        prefix="RMZ_", search="", replace="",
    ),
    dict(
        name="FreeAnims",
        # src skeleton: UE5 Manny (/Game/FreeAnimationsPack/Demo/Characters/Mannequins/Meshes/SK_Mannequin)
        source_mesh="/Game/FreeAnimationsPack/Demo/Characters/Mannequins/Meshes/SKM_Manny",
        target_mesh=UEFN_MESH,
        source_rig_name="IK_FreeAnims_UE5Manny",
        target_rig_name="IK_UEFN_Mannequin_Auto",
        retargeter=RTG_DIR + "/RTG_FreeAnims_to_UEFN",
        anim_folders=["/Game/FreeAnimationsPack/Animations"],
        classes=("AnimSequence", "AnimMontage"),
        include_regex="",
        out_folder="/Game/Retargeted_Animations/FreeAnims",
        prefix="FAP_", search="", replace="",
    ),
    dict(
        name="StoneGolem",
        # src skeleton: SK_UEFN_Mannequin -> tgt skeleton: /Game/Stone_Golem/mesh/SK_Stone_Golem_Skeleton
        source_mesh=UEFN_MESH,
        target_mesh=GOLEM_MESH,
        source_rig_name="IK_UEFN_Mannequin_Auto",
        target_rig_name="IK_Stone_Golem",
        retargeter=RTG_DIR + "/RTG_UEFN_to_StoneGolem",
        # Anim-director batch: the hero's combat sequences that the golem
        # minion needs (integrate_golem_minion.py finds them by the
        # attack/death name heuristics -- hence the search/replace rename).
        anim_folders=["/Game/Retargeted_Animations"],
        classes=("AnimSequence",),      # sequences only; golem montages are
                                        # built by integrate_golem_minion.py
        # hit_f_seq/hit_b_seq: golem flinch source (wire's step 7 builds
        # AM_GLM_Hit_F from a non-death 'hit' sequence; without one the
        # golem has no flinch montage).
        include_regex=r"(?i)^(combo_01-\d.*|hit_death_seq|knock_down_death_seq"
                      r"|hit_f_seq|hit_b_seq)$",
        # FOLDER CONTRACT: wire_new_animations.py GOLEM_RT_DIR and
        # integrate_golem_minion.py both read this folder -- keep in sync.
        out_folder="/Game/Arena/Minions/GolemAnims",
        prefix="GOL_", search="Combo_01-", replace="Attack_0",
    ),
]

# The ONLY roots this script may create/save assets under.
ALLOWED_PREFIXES = tuple(
    [RTG_DIR + "/"] + [p["out_folder"] + "/" for p in PAIRS])

# Canonical chain-name constants (FCharacterizationStandard, verified in
# IKRigAutoCharacterizer.cpp) -- the fuzzy mapper MUST emit these names.
CN_SPINE, CN_NECK, CN_HEAD = "Spine", "Neck", "Head"
CN_LEG = {"L": "LeftLeg", "R": "RightLeg"}
CN_CLAV = {"L": "LeftClavicle", "R": "RightClavicle"}
CN_ARM = {"L": "LeftArm", "R": "RightArm"}

STEP_RESULTS = []   # (label, "PASS"/"FAIL"/"SKIP", detail)
MANUAL_NOTES = []
_OP_COUNT = [0]


# ---------------------------------------------------------------------------
# Logging / bookkeeping / save helpers
# ---------------------------------------------------------------------------

def log(msg):
    unreal.log("%s %s" % (TAG, msg))


def warn(msg):
    unreal.log_warning("%s %s" % (TAG, msg))


def err(msg):
    unreal.log_error("%s %s" % (TAG, msg))


def record(label, status, detail=""):
    STEP_RESULTS.append((label, status, detail))
    (log if status != "FAIL" else warn)("%s: %s  %s" % (status, label, detail))


def manual(pair_name, text):
    line = "MANUAL [%s]: %s" % (pair_name, text)
    MANUAL_NOTES.append(line)
    warn(line)


def gc_tick(force=False):
    _OP_COUNT[0] += 1
    if force or _OP_COUNT[0] % GC_EVERY == 0:
        try:
            unreal.SystemLibrary.collect_garbage()
        except Exception:
            pass


def assert_allowed(asset_path):
    if not any(asset_path.startswith(p) or asset_path + "/" == p
               for p in ALLOWED_PREFIXES):
        raise RuntimeError("REFUSING to write outside owned folders: %s" % asset_path)


def force_save_asset(asset):
    """Proven force-save: mark dirty -> save(only_if_is_dirty=False) -> verify
    the .uasset mtime advanced on disk (dirty-gated saves silently wrote
    NOTHING earlier in this project)."""
    pkg_name = asset.get_outer().get_name()
    assert_allowed(pkg_name)
    try:
        asset.get_outer().mark_package_dirty()
    except Exception:
        pass
    disk_path = None
    if pkg_name.startswith("/Game/"):
        disk_path = os.path.join(
            unreal.Paths.project_content_dir(), pkg_name[len("/Game/"):] + ".uasset")
    before = os.path.getmtime(disk_path) if disk_path and os.path.isfile(disk_path) else None
    if not unreal.EditorAssetLibrary.save_loaded_asset(asset, only_if_is_dirty=False):
        raise RuntimeError("save_loaded_asset failed for %s" % asset.get_path_name())
    if before is not None:
        after = os.path.getmtime(disk_path)
        if after <= before:
            raise RuntimeError("save reported success but %s was NOT rewritten on disk"
                               % disk_path)
    gc_tick()


# ---------------------------------------------------------------------------
# Feature detection (5.x python-binding drift)
# ---------------------------------------------------------------------------

def meth(obj, *names):
    """First callable attribute among candidate python names, else None."""
    for n in names:
        fn = getattr(obj, n, None)
        if callable(fn):
            return fn
    return None


def enum_member(enum_name, *members):
    e = getattr(unreal, enum_name, None)
    if e is None:
        return None
    for m in members:
        v = getattr(e, m, None)
        if v is not None:
            return v
    return None


def preflight():
    """Verify the python surface this script depends on. Returns a dict of
    booleans; missing pieces degrade per-pair rather than abort, EXCEPT the
    plugin being off entirely."""
    caps = {
        "rig_class": hasattr(unreal, "IKRigDefinition"),
        "rig_ctrl": hasattr(unreal, "IKRigController"),
        "rig_factory": hasattr(unreal, "IKRigDefinitionFactory"),
        "rtg_class": hasattr(unreal, "IKRetargeter"),
        "rtg_ctrl": hasattr(unreal, "IKRetargeterController"),
        "rtg_factory": hasattr(unreal, "IKRetargetFactory"),
        "batch": hasattr(unreal, "IKRetargetBatchOperation")
                 and hasattr(unreal.IKRetargetBatchOperation, "duplicate_and_retarget"),
        "src_or_tgt": enum_member("RetargetSourceOrTarget", "SOURCE") is not None,
        "automap_enum": enum_member("AutoMapChainType", "EXACT") is not None,
    }
    for k, v in sorted(caps.items()):
        log("capability %-14s : %s" % (k, "OK" if v else "MISSING"))
    return caps


MANUAL_RECIPE = (
    "Content Browser -> right-click the SOURCE skeletal mesh (%(src)s) -> "
    "Create -> IK Rig -> IK Rig (open it; if chains are empty use Auto "
    "Create Retarget Chains + set the pelvis as Retarget Root). Repeat for "
    "the TARGET mesh (%(tgt)s). Then right-click the source mesh -> Create "
    "-> IK Retargeter -> pick the target IK Rig, open it, Auto-Map Chains "
    "(Exact), Auto Align if the rest poses differ, save as %(rtg)s. Batch: "
    "edit the constants at the top of Tools/batch_retarget_anims.py "
    "(RETARGETER_ASSET=%(rtg)s, SOURCE_FOLDER=%(anim)s, TARGET_FOLDER="
    "%(out)s, PREFIX=%(prefix)s) and run it from the editor Cmd console.")


def print_manual(pair, why):
    manual(pair["name"], why + "  Recipe: " + MANUAL_RECIPE % dict(
        src=pair["source_mesh"], tgt=pair["target_mesh"],
        rtg=pair["retargeter"], anim=";".join(pair["anim_folders"]),
        out=pair["out_folder"], prefix=pair["prefix"]))


# ---------------------------------------------------------------------------
# Asset scanning helpers
# ---------------------------------------------------------------------------

def asset_class_name(asset_data):
    """Class name off an AssetData across the 5.x drift (same helper as the
    proven batch_retarget_anims.py)."""
    try:
        return str(asset_data.asset_class_path.asset_name)
    except AttributeError:
        pass
    try:
        return str(asset_data.get_editor_property("asset_class"))
    except Exception:
        return ""


def list_assets_of(folders, classes, include_regex=""):
    """[(path, AssetData)] for matching assets under the given /Game folders."""
    rx = re.compile(include_regex) if include_regex else None
    out = []
    for folder in folders:
        if not unreal.EditorAssetLibrary.does_directory_exist(folder):
            warn("anim folder does not exist: %s" % folder)
            continue
        for path in unreal.EditorAssetLibrary.list_assets(
                folder, recursive=True, include_folder=False):
            ad = unreal.EditorAssetLibrary.find_asset_data(str(path))
            if asset_class_name(ad) not in classes:
                continue
            name = str(ad.asset_name)
            if rx is not None and not rx.match(name):
                continue
            out.append((str(path), ad))
    return sorted(out, key=lambda t: t[0].lower())


def load_mesh(path, what):
    mesh = unreal.EditorAssetLibrary.load_asset(path)
    if mesh is None or not isinstance(mesh, unreal.SkeletalMesh):
        raise RuntimeError("%s is not a loadable SkeletalMesh: %s" % (what, path))
    return mesh


def skeleton_path_of(obj):
    try:
        skel = obj.get_editor_property("skeleton")
        return skel.get_path_name() if skel else ""
    except Exception:
        return ""


def resolve_source_mesh(pair):
    """Load pair['source_mesh'] and VERIFY the pack's anims actually animate
    its skeleton; on mismatch, rediscover a mesh for the dominant skeleton."""
    mesh = load_mesh(pair["source_mesh"], "source_mesh")
    if not pair["anim_folders"]:
        return mesh
    # Sample the pack's sequences and tally their skeletons (registry tag =
    # cheap; no loading).
    tally = {}
    sample = list_assets_of(pair["anim_folders"], ("AnimSequence",),
                            pair.get("include_regex", ""))[:60]
    for _, ad in sample:
        try:
            skel_tag = str(ad.get_tag_value("Skeleton") or "")
        except Exception:
            skel_tag = ""
        if skel_tag:
            tally[skel_tag] = tally.get(skel_tag, 0) + 1
    if not tally:
        warn("[%s] no AnimSequences found to verify the source skeleton "
             "against -- trusting %s" % (pair["name"], pair["source_mesh"]))
        return mesh
    dominant = max(tally, key=tally.get)
    mesh_skel = skeleton_path_of(mesh)
    if mesh_skel and mesh_skel in dominant:
        log("[%s] source mesh skeleton verified against %d pack anims (%s)"
            % (pair["name"], sum(tally.values()), mesh_skel))
        return mesh
    warn("[%s] source mesh skeleton MISMATCH: mesh=%s pack-dominant=%s -- "
         "rediscovering a compatible SkeletalMesh" % (pair["name"], mesh_skel, dominant))
    # Find a SkeletalMesh whose registry Skeleton tag matches the dominant
    # skeleton: pack folders first, then /Game-wide.
    roots = [f.rsplit("/", 1)[0] for f in pair["anim_folders"]] + ["/Game"]
    for root in roots:
        for path in unreal.EditorAssetLibrary.list_assets(root, recursive=True,
                                                          include_folder=False):
            ad = unreal.EditorAssetLibrary.find_asset_data(str(path))
            if asset_class_name(ad) != "SkeletalMesh":
                continue
            try:
                if str(ad.get_tag_value("Skeleton") or "") == dominant:
                    m = load_mesh(str(path).split(".")[0], "rediscovered source mesh")
                    warn("[%s] using rediscovered source mesh %s" % (pair["name"], path))
                    return m
            except Exception:
                continue
    raise RuntimeError("no SkeletalMesh found for the pack's skeleton %s" % dominant)


# ---------------------------------------------------------------------------
# Bone reading (for the fuzzy mapper) -- no level is ever saved
# ---------------------------------------------------------------------------

def read_bones(mesh):
    """-> (ordered bone list [parents precede children], {bone: parent}).
    Strategy 1: transient SkeletalMeshComponent (pure ref-skeleton data reads,
    no registration needed). Strategy 2: temp SkeletalMeshActor spawned far
    below the arena, destroyed immediately (level NEVER saved)."""
    def read_from(comp):
        setter = meth(comp, "set_skeletal_mesh_asset", "set_skeletal_mesh")
        if setter is None:
            comp.set_editor_property("skeletal_mesh_asset", mesh)
        else:
            setter(mesh)
        n = comp.get_num_bones()
        if n <= 0:
            raise RuntimeError("component reports 0 bones")
        bones = [str(comp.get_bone_name(i)) for i in range(n)]
        parents = {b: str(comp.get_parent_bone(b)) for b in bones}
        return bones, parents

    try:
        comp = unreal.new_object(unreal.SkeletalMeshComponent)
        return read_from(comp)
    except Exception as exc:
        warn("transient-component bone read failed (%s) -- spawning a temp "
             "SkeletalMeshActor instead" % exc)
    sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    actor = sub.spawn_actor_from_class(
        unreal.SkeletalMeshActor, unreal.Vector(0.0, 0.0, -100000.0))
    if actor is None:
        raise RuntimeError("could not spawn a temp SkeletalMeshActor to read bones")
    try:
        comp = actor.get_editor_property("skeletal_mesh_component")
        return read_from(comp)
    finally:
        try:
            sub.destroy_actor(actor)
        except Exception:
            pass
        gc_tick()


# ---------------------------------------------------------------------------
# Fuzzy chain mapping (unknown skeletons, e.g. Stone Golem)
# ---------------------------------------------------------------------------

_PELVIS_RX = re.compile(r"pelvis|hips|\bhip\b|waist|\bcog\b")
_SPINE_RX = re.compile(r"spine|chest|torso|\bbody\b")
_NECK_RX = re.compile(r"neck")
_HEAD_RX = re.compile(r"head")
_HAND_RX = re.compile(r"hand|wrist|palm")
_FOOT_RX = re.compile(r"foot|ankle")
_TOE_RX = re.compile(r"\btoe|ball")
_CLAV_RX = re.compile(r"clavicle|collar|scap|shoulder")


def side_of(name):
    n = name.lower()
    toks = re.split(r"[^a-z0-9]+", n)
    if "l" in toks or "left" in toks or n.endswith("_l") or n.startswith("l_") or "left" in n:
        return "L"
    if "r" in toks or "right" in toks or n.endswith("_r") or n.startswith("r_") or "right" in n:
        return "R"
    return ""


def _first(bones, rx, side=None):
    for b in bones:
        if rx.search(b.lower()) and (side is None or side_of(b) == side):
            return b
    return None


def _walk_up(bone, parents, stop_rx):
    """Path [bone, parent, ...] ending just BELOW the first ancestor matching
    stop_rx (or the root). Returns the path list."""
    path = [bone]
    while True:
        p = parents.get(path[-1], "None")
        if p in ("", "None") or stop_rx.search(p.lower()):
            return path
        path.append(p)


def build_fuzzy_chains(bones, parents, pair_name):
    """-> (pelvis, [(chain_name, start_bone, end_bone)]). Name+topology based:
    hand/foot/head/pelvis are the most conserved names across rigs; chain
    starts are found by walking UP the real hierarchy, not by name guessing."""
    pelvis = _first(bones, _PELVIS_RX)
    chains = []
    if pelvis is None:
        raise RuntimeError("no pelvis-like bone (pelvis|hips|hip|waist|cog) "
                           "among: %s" % ", ".join(bones[:20]))
    spine_bones = [b for b in bones if _SPINE_RX.search(b.lower()) and side_of(b) == ""]
    if spine_bones:
        chains.append((CN_SPINE, spine_bones[0], spine_bones[-1]))
    neck_bones = [b for b in bones if _NECK_RX.search(b.lower())]
    if neck_bones:
        chains.append((CN_NECK, neck_bones[0], neck_bones[-1]))
    head = _first(bones, _HEAD_RX)
    if head:
        chains.append((CN_HEAD, head, head))
    boundary_rx = re.compile("%s|%s" % (_SPINE_RX.pattern, _PELVIS_RX.pattern))
    for side in ("L", "R"):
        hand = _first(bones, _HAND_RX, side)
        if hand:
            path = _walk_up(hand, parents, boundary_rx)
            top = path[-1]
            if _CLAV_RX.search(top.lower()) and len(path) > 1:
                chains.append((CN_CLAV[side], top, top))
                chains.append((CN_ARM[side], path[-2], hand))
            else:
                chains.append((CN_ARM[side], top, hand))
        foot = _first(bones, _FOOT_RX, side)
        if foot:
            toe = _first(bones, _TOE_RX, side)
            path = _walk_up(foot, parents, _PELVIS_RX)
            chains.append((CN_LEG[side], path[-1], toe if toe else foot))
    # Loud audit table.
    log("[%s] FUZZY BONE MAP (pelvis=%s):" % (pair_name, pelvis))
    log("  %-16s %-28s %s" % ("chain", "start", "end"))
    used = {pelvis}
    for cn, s, e in chains:
        log("  %-16s %-28s %s" % (cn, s, e))
        used.update((s, e))
    unmapped = [b for b in bones if b not in used]
    log("[%s] %d bones total, %d anchored to chains; unmapped (intermediate/"
        "extra): %s%s" % (pair_name, len(bones), len(used), ", ".join(unmapped[:40]),
                          " ..." if len(unmapped) > 40 else ""))
    # Fail LOUDLY on missing essentials (pelvis is checked above): a torso- or
    # limb-less chain set retargets to visibly broken animation. Head/Neck/
    # Clavicle stay optional.
    essential = (CN_SPINE, CN_LEG["L"], CN_LEG["R"], CN_ARM["L"], CN_ARM["R"])
    have = {cn for cn, _s, _e in chains}
    missing_ess = [cn for cn in essential if cn not in have]
    if missing_ess:
        raise RuntimeError(
            "fuzzy mapper missing essential chain(s): %s -- refusing to build "
            "a broken retarget mapping; fix the bone-name regexes or author "
            "the IK Rig by hand (see the table above)" % ", ".join(missing_ess))
    return pelvis, chains


# ---------------------------------------------------------------------------
# IK Rig creation
# ---------------------------------------------------------------------------

def create_or_load_rig(rig_name, mesh, pair_name):
    """Create (or reuse) /Game/Arena/Retargeters/<rig_name> bound to mesh.
    Returns (rig, used_template: bool). Raises on hard failure."""
    rig_path = "%s/%s" % (RTG_DIR, rig_name)
    if unreal.EditorAssetLibrary.does_asset_exist(rig_path):
        rig = unreal.EditorAssetLibrary.load_asset(rig_path)
        if rig is None or not isinstance(rig, unreal.IKRigDefinition):
            raise RuntimeError("%s exists but is not an IKRigDefinition" % rig_path)
        ctrl = unreal.IKRigController.get_controller(rig)
        existing_mesh = ctrl.get_skeletal_mesh()
        if existing_mesh is None or existing_mesh.get_path_name() != mesh.get_path_name():
            raise RuntimeError(
                "%s exists but is bound to %s, not %s -- refusing to overwrite; "
                "delete it or rename the pair's rig_name"
                % (rig_path, existing_mesh.get_path_name() if existing_mesh else "None",
                   mesh.get_path_name()))
        n_chains = len(list(ctrl.get_retarget_chains()))
        if n_chains > 0:
            log("[%s] reusing existing rig %s (%d chains) -- idempotent skip"
                % (pair_name, rig_path, n_chains))
            return rig, True   # configured earlier by us/editor: trust it
        log("[%s] rig %s exists but has 0 chains -- reconfiguring it"
            % (pair_name, rig_path))
    else:
        rig = None
        creator = getattr(unreal.IKRigDefinitionFactory, "create_new_ik_rig_asset", None) \
            if hasattr(unreal, "IKRigDefinitionFactory") else None
        if creator is not None:
            rig = creator(RTG_DIR, rig_name)
        if rig is None:
            tools = unreal.AssetToolsHelpers.get_asset_tools()
            rig = tools.create_asset(rig_name, RTG_DIR, unreal.IKRigDefinition,
                                     unreal.IKRigDefinitionFactory())
        if rig is None:
            raise RuntimeError("could not create IK Rig asset %s" % rig_path)
        log("[%s] created IK Rig %s" % (pair_name, rig_path))
    gc_tick()

    ctrl = unreal.IKRigController.get_controller(rig)
    if not ctrl.set_skeletal_mesh(mesh):
        raise RuntimeError("SetSkeletalMesh(%s) failed on %s"
                           % (mesh.get_name(), rig_path))

    # THE auto-chain magic: the same template characterizer behind the
    # editor's right-click auto-retarget flow.
    used_template = False
    auto_gen = meth(ctrl, "apply_auto_generated_retarget_definition")
    if auto_gen is not None:
        try:
            used_template = bool(auto_gen())
        except Exception as exc:
            warn("[%s] ApplyAutoGeneratedRetargetDefinition raised: %s"
                 % (pair_name, exc))
    else:
        warn("[%s] apply_auto_generated_retarget_definition missing from the "
             "bindings -- going straight to the fuzzy mapper" % pair_name)

    n_chains = len(list(ctrl.get_retarget_chains()))
    if used_template and n_chains > 0:
        log("[%s] template characterization matched: %d chains on %s"
            % (pair_name, n_chains, rig_name))
        # Optional FBIK polish (goals/solver). The retargeter disables the
        # Run-IK op anyway (editor parity), so failure here is cosmetic.
        fbik = meth(ctrl, "apply_auto_fbik")
        if fbik is not None:
            try:
                fbik()
            except Exception as exc:
                warn("[%s] ApplyAutoFBIK failed (non-fatal, IK op is disabled "
                     "anyway): %s" % (pair_name, exc))
        return rig, True
    if n_chains > 0:
        warn("[%s] characterizer produced %d chains WITHOUT a template match "
             "-- keeping them (verify the table in the retargeter step)"
             % (pair_name, n_chains))
        return rig, False

    # ---- fuzzy fallback (unknown skeleton, e.g. the golem) ----
    log("[%s] no template match for %s -- building chains from bone names"
        % (pair_name, mesh.get_name()))
    bones, parents = read_bones(mesh)
    pelvis, chains = build_fuzzy_chains(bones, parents, pair_name)
    set_root = meth(ctrl, "set_retarget_root", "set_pelvis_bone")
    if set_root is None:
        raise RuntimeError("neither set_retarget_root nor set_pelvis_bone "
                           "exists on IKRigController -- API drift")
    if not set_root(pelvis):
        raise RuntimeError("SetRetargetRoot(%s) failed" % pelvis)
    made = 0
    for cn, s, e in chains:
        try:
            created = ctrl.add_retarget_chain(cn, s, e, "None")
            if str(created) not in ("", "None"):
                made += 1
            else:
                warn("[%s] chain %s (%s -> %s) rejected by the rig" % (pair_name, cn, s, e))
        except Exception as exc:
            warn("[%s] chain %s (%s -> %s) raised: %s" % (pair_name, cn, s, e, exc))
    # VERIFY by re-read (write-back paranoia rule).
    n_chains = len(list(ctrl.get_retarget_chains()))
    got_root = "?"
    get_root = meth(ctrl, "get_retarget_root", "get_pelvis_bone")
    if get_root is not None:
        try:
            got_root = str(get_root())
        except Exception:
            pass
    log("[%s] fuzzy rig result: %d/%d chains stuck, pelvis re-read=%s"
        % (pair_name, n_chains, len(chains), got_root))
    if n_chains == 0 or made == 0:
        raise RuntimeError("fuzzy chain setup produced 0 usable chains")
    return rig, False


# ---------------------------------------------------------------------------
# IK Retargeter creation / wiring
# ---------------------------------------------------------------------------

SRC = enum_member("RetargetSourceOrTarget", "SOURCE")
TGT = enum_member("RetargetSourceOrTarget", "TARGET")


def rig_path_of(rig):
    return rig.get_path_name().split(".")[0] if rig else ""


def create_or_load_retargeter(pair, src_rig, tgt_rig, src_mesh, tgt_mesh,
                              both_template):
    rtg_path = pair["retargeter"]
    name = rtg_path.rsplit("/", 1)[1]
    rtg, needs_config = None, True
    if unreal.EditorAssetLibrary.does_asset_exist(rtg_path):
        rtg = unreal.EditorAssetLibrary.load_asset(rtg_path)
        if rtg is None or not isinstance(rtg, unreal.IKRetargeter):
            raise RuntimeError("%s exists but is not an IKRetargeter" % rtg_path)
        rc = unreal.IKRetargeterController.get_controller(rtg)
        cur_src = rc.get_ik_rig(SRC)
        cur_tgt = rc.get_ik_rig(TGT)
        if (not FORCE_RECONFIGURE
                and rig_path_of(cur_src) == rig_path_of(src_rig)
                and rig_path_of(cur_tgt) == rig_path_of(tgt_rig)
                and count_mapped_chains(rc, tgt_rig)[0] > 0):
            log("[%s] reusing existing retargeter %s (rigs match, chains "
                "mapped) -- idempotent skip" % (pair["name"], rtg_path))
            return rtg, False
        warn("[%s] %s exists but needs (re)wiring -- reconfiguring"
             % (pair["name"], rtg_path))
    else:
        tools = unreal.AssetToolsHelpers.get_asset_tools()
        rtg = tools.create_asset(name, RTG_DIR, unreal.IKRetargeter,
                                 unreal.IKRetargetFactory())
        if rtg is None:
            raise RuntimeError("could not create IK Retargeter %s" % rtg_path)
        log("[%s] created IK Retargeter %s" % (pair["name"], rtg_path))
    gc_tick()

    # ---- the editor auto-flow recipe (FProceduralRetargetAssets parity) ----
    rc = unreal.IKRetargeterController.get_controller(rtg)
    rc.set_ik_rig(SRC, src_rig)
    rc.set_ik_rig(TGT, tgt_rig)

    # 5.8 op stack. NOTE (from the engine source): ops must exist BEFORE the
    # retarget-pose work; SetIKRig(Target) does NOT auto-assign into ops.
    if meth(rc, "remove_all_ops") and meth(rc, "add_default_ops"):
        rc.remove_all_ops()
        rc.add_default_ops()
        assign_all = meth(rc, "assign_ik_rig_to_all_ops")
        if assign_all is not None:
            try:  # belt & braces: some ops keep their own target-rig slot
                assign_all(TGT, tgt_rig)
            except Exception as exc:
                warn("[%s] AssignIKRigToAllOps failed (default ops usually "
                     "self-assign): %s" % (pair["name"], exc))
    else:
        warn("[%s] op-stack API missing (pre-5.7 style retargeter?) -- "
             "relying on asset-level chain settings" % pair["name"])

    # Chain mapping: Exact for template rigs (editor default -- fuzzy can map
    # toes to fingers), Fuzzy when either side came from the fuzzy mapper.
    map_mode = enum_member("AutoMapChainType", "EXACT") if both_template \
        else enum_member("AutoMapChainType", "FUZZY")
    if map_mode is None:
        raise RuntimeError("unreal.AutoMapChainType missing -- API drift")
    rc.auto_map_chains(map_mode, True)   # op_name omitted -> ALL ops

    # Regenerate + auto-align the target retarget pose (A- vs T-pose fix).
    try:
        pose = rc.get_current_retarget_pose_name(TGT)
        rc.reset_retarget_pose(pose, [], TGT)
        if AUTO_ALIGN and pair.get("auto_align", True):
            align = meth(rc, "auto_align_all_bones")
            if align is not None:
                try:
                    align(TGT)
                except TypeError:
                    m = enum_member("RetargetAutoAlignMethod", "CHAIN_TO_CHAIN")
                    align(TGT, m)
    except Exception as exc:
        warn("[%s] retarget-pose regen/auto-align failed (fix in the "
             "retargeter editor if the output looks twisted): %s"
             % (pair["name"], exc))

    # Disable the Run-IK op -- editor auto-flow parity ("auto-IK is not yet
    # robust"); FK chains + pelvis motion carry the retarget.
    try:
        n_ops = rc.get_num_retarget_ops()
        for i in range(n_ops):
            opc = None
            get_opc = meth(rc, "get_op_controller")
            if get_opc is not None:
                try:
                    opc = get_opc(i)
                except Exception:
                    opc = None
            label = type(opc).__name__ if opc is not None else str(rc.get_op_name(i))
            if "runikrig" in label.lower().replace(" ", "") or "runik" in label.lower():
                rc.set_retarget_op_enabled(i, False)
                log("[%s] disabled op %d (%s)" % (pair["name"], i, label))
    except Exception as exc:
        warn("[%s] could not disable the Run-IK op (harmless if FBIK was "
             "never added): %s" % (pair["name"], exc))

    # Preview meshes: batch_retarget_anims.py-style consumers read these.
    try:
        rc.set_preview_mesh(SRC, src_mesh)
        rc.set_preview_mesh(TGT, tgt_mesh)
    except Exception as exc:
        warn("[%s] SetPreviewMesh failed: %s" % (pair["name"], exc))
    return rtg, True


def count_mapped_chains(rc, tgt_rig):
    """(mapped, total, [(target_chain, source_chain)]) read back from the
    retargeter -- the verify-every-questionable-write rule."""
    rows, mapped = [], 0
    try:
        tgt_ctrl = unreal.IKRigController.get_controller(tgt_rig)
        for chain in tgt_ctrl.get_retarget_chains():
            try:
                cn = str(chain.get_editor_property("chain_name"))
            except Exception:
                continue
            try:
                src = str(rc.get_source_chain(cn))
            except Exception:
                src = "?"
            rows.append((cn, src))
            if src not in ("", "None", "?"):
                mapped += 1
    except Exception as exc:
        warn("chain-mapping read-back failed: %s" % exc)
    return mapped, len(rows), rows


# ---------------------------------------------------------------------------
# Batch retarget (local reimplementation of the PROVEN call handling in
# Tools/batch_retarget_anims.py -- that file is deliberately not imported:
# it executes main() at module scope)
# ---------------------------------------------------------------------------

def expected_output_name(pair, src_name):
    n = src_name
    if pair["search"]:
        n = n.replace(pair["search"], pair["replace"])
    return pair["prefix"] + n


def run_batch(pair, rtg, src_mesh, tgt_mesh):
    if not pair["prefix"]:
        raise RuntimeError("prefix must be non-empty (pre-5.8 fallback "
                           "duplicates land NEXT TO sources; empty prefix "
                           "would collide with the originals)")
    candidates = list_assets_of(pair["anim_folders"], pair["classes"],
                                pair.get("include_regex", ""))
    out_folder = pair["out_folder"]
    to_retarget, skipped = [], 0
    for path, ad in candidates:
        if path.startswith(out_folder + "/"):
            continue
        name = str(ad.asset_name)
        if name.startswith(pair["prefix"]):
            skipped += 1
            continue   # leftover output from a prior failed move
        if unreal.EditorAssetLibrary.does_asset_exist(
                "%s/%s" % (out_folder, expected_output_name(pair, name))):
            skipped += 1
            continue
        to_retarget.append(ad)
    if not to_retarget:
        return 0, 0, skipped
    # Flat-output name-collision guard (same rationale as the proven script).
    counts = {}
    for ad in to_retarget:
        n = expected_output_name(pair, str(ad.asset_name))
        counts[n] = counts.get(n, 0) + 1
    dupes = sorted(n for n, c in counts.items() if c > 1)
    if dupes:
        raise RuntimeError("output name collision(s) into flat %s: %s -- "
                           "retarget subfolders separately or change the "
                           "prefix" % (out_folder, ", ".join(dupes[:8])))
    if not unreal.EditorAssetLibrary.does_directory_exist(out_folder):
        unreal.EditorAssetLibrary.make_directory(out_folder)
    log("[%s] batch retargeting %d asset(s): %s -> %s via %s ..."
        % (pair["name"], len(to_retarget), src_mesh.get_name(),
           tgt_mesh.get_name(), pair["retargeter"]))
    created, moved_needed = None, False
    # Primary (5.8+): RunBatchRetarget(FIKRetargetBatchOperationInputs) --
    # DuplicateAndRetarget is UE_DEPRECATED(5.8) in the engine source.
    if hasattr(unreal.IKRetargetBatchOperation, "run_batch_retarget") \
            and hasattr(unreal, "IKRetargetBatchOperationInputs"):
        try:
            inputs = unreal.IKRetargetBatchOperationInputs()
            inputs.set_editor_property("assets_to_retarget", to_retarget)
            inputs.set_editor_property("source_mesh", src_mesh)
            inputs.set_editor_property("target_mesh", tgt_mesh)
            inputs.set_editor_property("ik_retarget_asset", rtg)
            inputs.set_editor_property("search", pair["search"])
            inputs.set_editor_property("replace", pair["replace"])
            inputs.set_editor_property("prefix", pair["prefix"])
            inputs.set_editor_property("target_path", out_folder)
            created = unreal.IKRetargetBatchOperation.run_batch_retarget(inputs)
        except Exception as exc:
            warn("[%s] RunBatchRetarget path failed (%s) -- falling back to "
                 "duplicate_and_retarget" % (pair["name"], exc))
            created = None
    if created is None:
        # Fallback: first 8 args positional (stable 5.2-5.8); target_path is
        # the 5.8 destination kwarg -- TypeError means older bindings, fall
        # back to duplicate-next-to-source + move (the proven handling from
        # Tools/batch_retarget_anims.py).
        try:
            created = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
                to_retarget, src_mesh, tgt_mesh, rtg,
                pair["search"], pair["replace"], pair["prefix"], "",
                target_path=out_folder)
        except TypeError:
            warn("[%s] pre-5.8 batch signature (no target_path) -- will move "
                 "outputs into %s" % (pair["name"], out_folder))
            created = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
                to_retarget, src_mesh, tgt_mesh, rtg,
                pair["search"], pair["replace"], pair["prefix"], "")
            moved_needed = True
    created_by_name = {}
    for ad in list(created or []):
        created_by_name.setdefault(str(ad.asset_name), ad)
    passed, failed = 0, 0
    for ad in to_retarget:
        want = expected_output_name(pair, str(ad.asset_name))
        got = created_by_name.get(want)
        if got is None:
            warn("[%s] batch FAIL: %s -> no output named %s (see retargeter "
                 "chain errors above)" % (pair["name"], ad.asset_name, want))
            failed += 1
            continue
        if moved_needed:
            old_path = str(got.package_name)
            dest = "%s/%s" % (out_folder, want)
            if old_path != dest and not unreal.EditorAssetLibrary.rename_asset(old_path, dest):
                warn("[%s] retargeted OK but move failed: %s -> %s (usable "
                     "where it is; move manually)" % (pair["name"], old_path, dest))
        passed += 1
    unreal.EditorAssetLibrary.save_directory(out_folder, only_if_is_dirty=True)
    gc_tick(force=True)
    return passed, failed, skipped


# ---------------------------------------------------------------------------
# Per-pair driver
# ---------------------------------------------------------------------------

def do_pair(pair, caps):
    name = pair["name"]

    # -- meshes --
    try:
        src_mesh = resolve_source_mesh(pair)
        tgt_mesh = load_mesh(pair["target_mesh"], "target_mesh")
        record("%s meshes" % name, "PASS",
               "%s -> %s" % (src_mesh.get_name(), tgt_mesh.get_name()))
    except Exception as exc:
        record("%s meshes" % name, "FAIL", str(exc))
        print_manual(pair, "Mesh resolution failed: %s." % exc)
        return

    # -- IK rigs --
    if not (caps["rig_class"] and caps["rig_ctrl"]):
        record("%s ik rigs" % name, "FAIL", "IKRig python surface missing")
        print_manual(pair, "IKRigDefinition/IKRigController not in the python "
                           "bindings (IK Rig plugin off?).")
        return
    try:
        src_rig, src_template = create_or_load_rig(
            pair["source_rig_name"], src_mesh, name)
        tgt_rig, tgt_template = create_or_load_rig(
            pair["target_rig_name"], tgt_mesh, name)
        record("%s ik rigs" % name, "PASS",
               "src=%s(template=%s) tgt=%s(template=%s)"
               % (pair["source_rig_name"], src_template,
                  pair["target_rig_name"], tgt_template))
    except Exception as exc:
        record("%s ik rigs" % name, "FAIL", str(exc))
        traceback.print_exc()
        print_manual(pair, "IK Rig creation failed: %s." % exc)
        return

    # -- retargeter --
    if not (caps["rtg_class"] and caps["rtg_ctrl"] and caps["src_or_tgt"]):
        record("%s retargeter" % name, "FAIL", "IKRetargeter python surface missing")
        print_manual(pair, "IKRetargeter/IKRetargeterController not in the "
                           "python bindings.")
        return
    try:
        rtg, configured = create_or_load_retargeter(
            pair, src_rig, tgt_rig, src_mesh, tgt_mesh,
            both_template=(src_template and tgt_template))
        rc = unreal.IKRetargeterController.get_controller(rtg)
        mapped, total, rows = count_mapped_chains(rc, tgt_rig)
        log("[%s] CHAIN MAPPING (target <- source):" % name)
        for cn, srcn in rows:
            log("  %-20s <- %s" % (cn, srcn))
        if total > 0 and mapped == 0:
            record("%s retargeter" % name, "FAIL",
                   "0/%d target chains mapped after AutoMapChains" % total)
            print_manual(pair, "AutoMapChains produced no mappings -- open "
                                "%s and map chains by hand." % pair["retargeter"])
            return
        record("%s retargeter" % name, "PASS",
               "%s (%d/%d chains mapped%s)"
               % (pair["retargeter"], mapped, total,
                  ", reconfigured" if configured else ", reused"))
    except Exception as exc:
        record("%s retargeter" % name, "FAIL", str(exc))
        traceback.print_exc()
        print_manual(pair, "Retargeter wiring failed: %s." % exc)
        return

    # -- save (rigs + retargeter) --
    try:
        for asset in (src_rig, tgt_rig, rtg):
            force_save_asset(asset)
        record("%s save" % name, "PASS", "rigs + retargeter force-saved, "
                                         "mtime-verified")
    except Exception as exc:
        record("%s save" % name, "FAIL", str(exc))
        return

    # -- batch --
    if not DO_BATCH:
        record("%s batch" % name, "SKIP", "DO_BATCH=False")
        return
    if not caps["batch"]:
        record("%s batch" % name, "FAIL",
               "IKRetargetBatchOperation.duplicate_and_retarget missing")
        print_manual(pair, "Batch API missing -- run Tools/"
                           "batch_retarget_anims.py from the editor instead.")
        return
    try:
        passed, failed, skipped = run_batch(pair, rtg, src_mesh, tgt_mesh)
        status = "PASS" if failed == 0 else ("FAIL" if passed == 0 else "PASS")
        record("%s batch" % name, status,
               "%d retargeted, %d failed, %d skipped (already done) -> %s"
               % (passed, failed, skipped, pair["out_folder"]))
    except Exception as exc:
        record("%s batch" % name, "FAIL", str(exc))
        traceback.print_exc()
    gc_tick(force=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    log("=== setup_retargeters: %d pair(s), DO_BATCH=%s ===" % (len(PAIRS), DO_BATCH))
    caps = preflight()
    if not (caps["rig_class"] or caps["rtg_class"]):
        err("IK Rig plugin surface entirely absent -- enable Edit -> Plugins "
            "-> 'IK Rig' and re-run. Printing manual recipes for all pairs.")
        for pair in PAIRS:
            print_manual(pair, "IK Rig plugin is disabled.")
    else:
        if not unreal.EditorAssetLibrary.does_directory_exist(RTG_DIR):
            unreal.EditorAssetLibrary.make_directory(RTG_DIR)
        for pair in PAIRS:
            if ONLY_PAIRS and pair["name"] not in ONLY_PAIRS:
                record("%s (pair)" % pair["name"], "SKIP",
                       "not in SETUP_RTG_PAIRS=%s" % ",".join(ONLY_PAIRS))
                continue
            log("--- PAIR %s ---" % pair["name"])
            try:
                do_pair(pair, caps)
            except Exception as exc:   # per-pair isolation: never abort the run
                record("%s (pair)" % pair["name"], "FAIL", str(exc))
                traceback.print_exc()
            gc_tick(force=True)

    log("=" * 60)
    log("SETUP-RETARGETERS SUMMARY")
    log("=" * 60)
    n_fail = 0
    for label, status, detail in STEP_RESULTS:
        line = "%-5s %-28s %s" % (status, label, detail)
        (warn if status == "FAIL" else log)(line)
        n_fail += status == "FAIL"
    for note in MANUAL_NOTES:
        warn(note)
    if n_fail:
        warn("%d step(s) FAILED -- see above. Everything that passed is "
             "saved and re-runnable (idempotent)." % n_fail)
    else:
        log("All steps passed. Retargeters live in %s; batch outputs in the "
            "per-pair folders. Reminder: batch outputs are per-character "
            "copies -- never share montages across characters (CLAUDE.md)."
            % RTG_DIR)


main()
